"""empty message

Revision ID: b06a2bd14bb2
Revises: 
Create Date: 2021-01-21 21:48:54.000522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06a2bd14bb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genre',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('genre_name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('genre_id')
    )
    op.create_index(op.f('ix_genre_genre_name'), 'genre', ['genre_name'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('book',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=64), nullable=True),
    sa.Column('book_author', sa.String(length=64), nullable=True),
    sa.Column('book_owner', sa.Integer(), nullable=True),
    sa.Column('book_genre', sa.Integer(), nullable=True),
    sa.Column('book_description', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['book_genre'], ['genre.genre_id'], ),
    sa.ForeignKeyConstraint(['book_owner'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('book_id')
    )
    op.create_index(op.f('ix_book_book_author'), 'book', ['book_author'], unique=False)
    op.create_index(op.f('ix_book_book_title'), 'book', ['book_title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_book_title'), table_name='book')
    op.drop_index(op.f('ix_book_book_author'), table_name='book')
    op.drop_table('book')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_genre_genre_name'), table_name='genre')
    op.drop_table('genre')
    # ### end Alembic commands ###
